extends Node

enum DessertType {DEFAULT, ICECREAMSCOOP, ICECREAMSHAKE, CAKE, SLUSHIE, POPSICLE, FROZENFRUIT}

enum Default {}

enum IceCreamScoop {CONE, CUP, VANILLA, CHOCOLATE, BERRY, MATCHA}

enum IceCreamShake {VANILLA, CHOCOLATE, MINT, COOKIE, CARAMEL, BLEND}
